package com.sojava.beehive.framework.component.log.bean;

// Generated 2014-4-10 17:33:38 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", schema = "base")
public class Log implements Serializable {
	private static final long serialVersionUID = -7397466119456655074L;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name="LOG_ID_GENERATOR", sequenceName="BASE.LOG_ID_SEQ", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="LOG_ID_GENERATOR")
	private Integer id;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "log_time", length = 29)
	private Date logTime;
	@Column(name = "organ_id", length = 200)
	private String organId;
	@Column(name = "log_level", length = 50)
	private String logLevel;
	@Column(name = "class_info", length = 200)
	private String classInfo;
	@Column(name = "kind", length = 100)
	private String kind;
	@Column(name = "action_type", length = 100)
	private String actionType;
	@Column(name = "module_id", length = 200)
	private String moduleId;
	@Column(name = "user_id", length = 200)
	private String userId;
	@Column(name = "item_id", length = 200)
	private String itemId;
	@Column(name = "client_type", length = 50)
	private String clientType;
	@Column(name = "client_ip", length = 200)
	private String clientIp;
	@Column(name = "message", length = 2000)
	private String message;

	public Log() {
		this.logTime = new Date();
	}

	public Log(String kind, String logLevel, String message) {
		this.kind = kind;
		this.logLevel = logLevel;
		this.message = message;
		this.logTime = new Date();
	}

	public Log(Date logTime, String organId, String logLevel,
			String classInfo, String kind, String actionType, String moduleId,
			String userId, String itemId, String clientType, String clientIp,
			String message) {
		this.logTime = logTime;
		this.organId = organId;
		this.logLevel = logLevel;
		this.classInfo = classInfo;
		this.kind = kind;
		this.actionType = actionType;
		this.moduleId = moduleId;
		this.userId = userId;
		this.itemId = itemId;
		this.clientType = clientType;
		this.clientIp = clientIp;
		this.message = message;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getLogTime() {
		return this.logTime;
	}

	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}

	public String getOrganId() {
		return this.organId;
	}

	public void setOrganId(String organId) {
		this.organId = organId;
	}

	public String getLogLevel() {
		return this.logLevel;
	}

	public void setLogLevel(String logLevel) {
		this.logLevel = logLevel;
	}

	public String getClassInfo() {
		return this.classInfo;
	}

	public void setClassInfo(String classInfo) {
		this.classInfo = classInfo;
	}

	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	public String getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	public String getClientType() {
		return this.clientType;
	}

	public void setClientType(String clientType) {
		this.clientType = clientType;
	}

	public String getClientIp() {
		return this.clientIp;
	}

	public void setClientIp(String clientIp) {
		this.clientIp = clientIp;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
